[package]
name = "chess_game_server"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
petname = { version = "2.0", default-features = false, features = ["default-words"] }
getrandom = { version = "0.2", features = ["custom"] }
spacetimedb = "2.0"
log = "0.4"
chess_core = {path = "../core"}